/** The shared UI components (§3.4). Every module builds its screens from these and the tokens. */
export { Button, IconButton, type ButtonProps, type ButtonSize, type ButtonVariant, type IconButtonProps } from './Button';
export { Chip, Keycap, Tag, roleWord, type ChipDot, type ChipProps, type TagProps } from './Chip';
export { Dialog, Sheet, type CloseReason, type DialogProps, type SheetProps } from './Dialog';
export { Field, TextArea, type FieldProps, type TextAreaProps } from './Field';
export { Footprints } from './Footprints';
export { KindIcon, kindWord } from './KindIcon';
export { LiveRegion } from './LiveRegion';
export { Menu, type MenuItem, type MenuProps } from './Menu';
export { Meter, type MeterProps } from './Meter';
export { Panel, PaperCard, StickyNote, type PanelProps, type PaperCardProps, type Tape } from './Panel';
export { PlaceholderGlyph, type GlyphRole, type PlaceholderGlyphProps } from './PlaceholderGlyph';
export { Popover, type Placement, type PopoverProps } from './Popover';
export { Segmented, type SegmentedOption, type SegmentedProps } from './Segmented';
export { Slider, type SliderProps } from './Slider';
export { Sticker, type StickerProps } from './Sticker';
export { TabPanel, Tabs, type TabDef, type TabsProps } from './Tabs';
export { ToastView } from './Toast';
export { Toggle, type ToggleProps } from './Toggle';
export { Tooltip, type TooltipProps } from './Tooltip';
export { Wordmark } from './Wordmark';
